### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by kutenai** [chris1111/Easy-Web-Drivers-Patcher#1]
What is this script doing? Why is it binary, and where is the source?

I'm not too keen on running a binary script on my system with no information about the code -- i.e. no access to the source.

**Comment by chris1111** [comment]
There is no Source, this is a Binary because I did it like that
The main Topic its here [Easy Web Drivers Patcher](https://www.hackintosh-montreal.com/t7269-easy-web-drivers-patcherl)
If you don't trust don't use it
